import {useEffect,useState} from 'react';
interface Modifier {name:string;type?:string;required?:boolean;options:{name:string;priceAdjustment:number}[];}
interface Item {id:string;name:string;description?:string;image?:string;price:string|number;tags:string[];modifiers?:Modifier[];preparationTimeMinutes:number;}
interface Selection {name:string;option:string;priceAdjustment:number;}
interface Line {key:string;item:Item;quantity:number;modifiers:Selection[];specialInstructions:string;}
interface Menu {restaurant:{name:string;logo?:string;currency:string};categories:{id:string;name:string;items:Item[]}[];paymentProviders:string[];}
declare global {interface Window {Razorpay?:new(options:Record<string,unknown>)=>{open:()=>void};}}
export function Storefront({qr=false}:{qr?:boolean}){
 const query=new URLSearchParams(window.location.search);const [outlet,setOutlet]=useState(query.get('outletId')||'');const [restaurant,setRestaurant]=useState(query.get('restaurant')||'');const [outlets,setOutlets]=useState<{id:string;name:string}[]>([]);const [menu,setMenu]=useState<Menu|null>(null);const [cart,setCart]=useState<Line[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [order,setOrder]=useState<{id:string;orderNumber?:string;status?:string;paymentStatus?:string;total?:number}|null>(query.get('orderId')?{id:query.get('orderId')!}:null);const [type,setType]=useState(qr?'dine-in':'takeaway');const [gateway,setGateway]=useState('stripe');const [filter,setFilter]=useState('');
 const base=import.meta.env?.VITE_API_URL||'';
 async function request(path:string,method='GET',body?:unknown,token?:string){const response=await fetch(base+'/api/public'+path,{method,headers:{'Content-Type':'application/json',...(token?{'x-order-token':token}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});const data=await response.json();if(!response.ok)throw new Error(data.error?.message||'Request failed');return data;}
 useEffect(()=>{if(!outlet)return;void request('/menu?outletId='+encodeURIComponent(outlet)).then(data=>{setMenu(data);setGateway(data.paymentProviders[0]||'stripe');}).catch(e=>setError(e.message));},[outlet]);
 useEffect(()=>{if(!order)return;const token=sessionStorage.getItem('dinely-order-'+order.id);if(!token){setError('Open this order on the device where you placed it.');return;}let cancelled=false;const refresh=()=>void request('/orders/'+order.id,'GET',undefined,token).then(data=>{if(!cancelled)setOrder(data);}).catch(e=>setError(e.message));refresh();const timer=window.setInterval(refresh,5000);return()=>{cancelled=true;window.clearInterval(timer);};},[order?.id]);
 const currency=menu?.restaurant.currency||'INR';const money=(amount:number)=>new Intl.NumberFormat(undefined,{style:'currency',currency}).format(amount);const total=cart.reduce((sum,line)=>sum+(Number(line.item.price)+line.modifiers.reduce((s,m)=>s+m.priceAdjustment,0))*line.quantity,0);
 async function checkout(id:string){const token=sessionStorage.getItem('dinely-order-'+id)!;const payment=await request('/orders/'+id+'/checkout','POST',{gateway},token);if(payment.url){window.location.assign(payment.url);return;}if(!window.Razorpay)await new Promise<void>((resolve,reject)=>{const script=document.createElement('script');script.src='https://checkout.razorpay.com/v1/checkout.js';script.onload=()=>resolve();script.onerror=()=>reject(new Error('Payment checkout could not load'));document.body.appendChild(script);});new window.Razorpay!({key:payment.key,order_id:payment.orderId,amount:payment.amount,currency:payment.currency,name:menu?.restaurant.name,handler:()=>setError('Payment received by checkout. Waiting for server confirmation…')}).open();}
 const style={padding:'12px',border:'1px solid #d9d4ca',borderRadius:'8px'};
 return <main style={{maxWidth:1100,margin:'auto',padding:24,fontFamily:'system-ui',color:'#2d302c'}}><header style={{borderBottom:'1px solid #e5dfd3',paddingBottom:20,marginBottom:24}}>{menu?.restaurant.logo&&<img src={menu.restaurant.logo} alt="Restaurant logo" width="60"/>}<h1>{menu?.restaurant.name||'Dinely ordering'}</h1><p>{qr?'Scan, choose and order at your table':'Order for pickup or delivery'}</p></header>{error&&<p role="alert" style={{color:'#a32b20'}}>{error}</p>}
 {order?<section><h2>Order {order.orderNumber}</h2><p>Status: {order.status||'Checking…'}</p><p>Payment: {order.paymentStatus||'Waiting for confirmation'}</p>{order.paymentStatus!=='PAID'&&<button style={style} disabled={busy} onClick={async()=>{setBusy(true);try{await checkout(order.id);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Retry payment</button>}<p>Keep this page open for order updates.</p></section>:<>
 {!outlet&&<form onSubmit={async e=>{e.preventDefault();try{setOutlets(await request('/outlets?restaurant='+encodeURIComponent(restaurant)));}catch(error){setError((error as Error).message);}}}><label>Restaurant <input style={style} value={restaurant} onChange={e=>setRestaurant(e.target.value)} required/></label><button style={style}>Find restaurant</button>{outlets.map(o=><button key={o.id} style={style} type="button" onClick={()=>setOutlet(o.id)}>{o.name}</button>)}</form>}
 {menu&&<><label>Filter menu <input style={style} value={filter} placeholder="Name or dietary tag" onChange={e=>setFilter(e.target.value)}/></label>{menu.categories.map(category=><section key={category.id}><h2>{category.name}</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(250px,1fr))',gap:18}}>{category.items.filter(item=>(item.name+' '+item.tags.join(' ')).toLowerCase().includes(filter.toLowerCase())).map(item=><form key={item.id} style={{...style,padding:20}} onSubmit={e=>{e.preventDefault();const values=new FormData(e.currentTarget);const selections:Selection[]=[];for(const group of item.modifiers??[])for(const selected of values.getAll('modifier:'+group.name)){if(!selected)continue;const option=group.options.find(o=>o.name===selected)!;selections.push({name:group.name,option:option.name,priceAdjustment:option.priceAdjustment});}setCart(lines=>[...lines,{key:crypto.randomUUID(),item,quantity:1,modifiers:selections,specialInstructions:String(values.get('instructions')||'')}]);}}>{item.image&&<img src={item.image} alt={item.name} style={{width:'100%',height:160,objectFit:'cover',borderRadius:8}}/>}<h3>{item.name} <small>{money(Number(item.price))}</small></h3><p>{item.description}</p><p>{item.tags.join(' / ')} · About {item.preparationTimeMinutes} min</p>{item.modifiers?.map(group=><label key={group.name} style={{display:'block',marginBottom:8}}>{group.name}{group.required?' *':''}<select style={style} name={'modifier:'+group.name} required={group.required} multiple={group.type==='multiple'}><option value="">Choose</option>{group.options.map(option=><option key={option.name} value={option.name}>{option.name} ({money(option.priceAdjustment)})</option>)}</select></label>)}<label>Instructions<input style={style} name="instructions" placeholder="Allergies or preferences"/></label><button style={{...style,background:'#f5c46d',marginTop:12}}>Add to order</button></form>)}</div></section>)}
 <section style={{background:'#fff8e9',padding:24,borderRadius:16,marginTop:24}}><h2>Your order</h2>{cart.map(line=><div key={line.key} style={{display:'flex',gap:12,alignItems:'center',marginBottom:12}}><span>{line.item.name} {line.modifiers.map(m=>m.option).join(', ')}</span><input aria-label={'Quantity for '+line.item.name} style={{...style,width:80}} type="number" min="1" value={line.quantity} onChange={e=>setCart(lines=>lines.map(l=>l.key===line.key?{...l,quantity:Math.max(1,Number(e.target.value))}:l))}/><button style={style} onClick={()=>setCart(lines=>lines.filter(l=>l.key!==line.key))}>Remove</button></div>)}<p>Items: {money(total)}. Final taxes and service charge are calculated at checkout.</p><form style={{display:'grid',gap:12,maxWidth:520}} onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const values=new FormData(e.currentTarget);try{const result=await request('/orders','POST',{outletId:outlet,type,tableId:qr?query.get('tableId'):undefined,customer:{name:values.get('name'),phone:values.get('phone')},...(type==='delivery'?{deliveryAddress:{line1:values.get('address'),city:values.get('city'),postalCode:values.get('postalCode')}}:{}),items:cart.map(l=>({menuItemId:l.item.id,quantity:l.quantity,modifiers:l.modifiers,specialInstructions:l.specialInstructions}))});sessionStorage.setItem('dinely-order-'+result.id,result.accessToken);setOrder(result);await checkout(result.id);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><label>Your name<input style={style} name="name" required autoComplete="name"/></label><label>Phone<input style={style} name="phone" type="tel" required autoComplete="tel"/></label>{!qr&&<label>Order type<select style={style} value={type} onChange={e=>setType(e.target.value)}><option value="takeaway">Pickup</option><option value="delivery">Delivery</option></select></label>}{type==='delivery'&&<><label>Street address<input style={style} name="address" required autoComplete="street-address"/></label><label>City<input style={style} name="city" required autoComplete="address-level2"/></label><label>Postal code<input style={style} name="postalCode" required autoComplete="postal-code"/></label></>}<label>Pay with<select style={style} value={gateway} onChange={e=>setGateway(e.target.value)}>{menu.paymentProviders.map(provider=><option key={provider}>{provider}</option>)}</select></label>{!menu.paymentProviders.length&&<p>Online ordering is unavailable until the restaurant configures payments.</p>}<button style={{...style,background:'#f5c46d'}} disabled={busy||!cart.length||!menu.paymentProviders.length}>Continue to secure payment</button></form></section></>}
 </> }</main>;
}
